# fly.toml app configuration file generated for bwaincell on 2025-10-04T11:32:59Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# Updated for PWA Phase 1: Backend API Integration
# This configuration supports both Discord bot and HTTP API server

app = 'bwaincell'
primary_region = 'iad'

[build]

[env]
  NODE_ENV = "production"
  API_PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1
  processes = ['app']

  # Health check configuration
  [[http_service.checks]]
    interval = "15s"
    timeout = "10s"
    grace_period = "30s"
    method = "GET"
    path = "/health"
    protocol = "http"

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[mounts]
  source = "bwaincell_data"
  destination = "/app/data"
  initial_size = "1gb"
