# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "bwaincell"
primary_region = "iad"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[env]
  NODE_ENV = "production"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Critical for Discord bots: prevent auto-shutdown
[[services]]
  internal_port = 8080
  protocol = "tcp"
  auto_start_machines = false
  auto_stop_machines = false
  min_machines_running = 1
