# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "bwaincell"
primary_region = "iad"

[build]

[env]
  NODE_ENV = "production"
  DATABASE_PATH = "./data/bwaincell.sqlite"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
